#!/usr/bin/env bash
#
# All-in-one script using all the common utilities.
# Copyright (c) 2023 - Jeremías Longo <jeremiaslongo@gmail.com>
#
# Built with shell-script-skeleton v0.1.0 <http://github.com/z017/shell-script-skeleton>

# Import common script configurations and utilities
source "$(cd "$(dirname $(realpath "${BASH_SOURCE[0]}"))" && pwd)/_common.sh" || exit 1

readonly SCRIPT_NAME=${0##*/}
readonly SCRIPT_VERSION=0.0.1
readonly SCRIPT_DESCRIPTION="All-in-one script"

# Long Options. To expect an argument for an option, just place a : (colon)
# after the proper option flag.
readonly LONG_OPTS=(help version log-level: force)

# Short Options. To expect an argument for an option, just place a : (colon)
# after the proper option flag.
readonly SHORT_OPTS=hv

# Script Commands
readonly COMMANDS=(help version log)

# List of required tools, example: REQUIRED_TOOLS=(git ssh)
readonly REQUIRED_TOOLS=()

# Force flag
declare FORCE=false

# Paths
readonly PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# -----------------------------------------------------------------------------
# Hooks
# -----------------------------------------------------------------------------
function on_init() {
  trace "> on_init"
  load_environment_if_exists "$PROJECT_ROOT/.env"
}

function on_option() {
  case "$1" in
    h|help)       execute_help ;;
    v|version)    execute_version ;;
    log-level)    log_level "$OPTARG" ;;
    force)        FORCE=true ;;
    *)            fatal "Internal script error, unmatched option '$1'" ;;
  esac
}

function before_execute() {
  readonly FORCE
}

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
function execute_command() {
  local cmd="$1"
  shift
  case "$cmd" in
    help)     execute_help ;;
    version)  execute_version ;;
    log)      execute_log ;;
    # default command
    *)        execute_default ;;
  esac
}

function execute_default() {
  info "$PROJECT_ROOT"
}

function execute_log() {
  trace "trace log"
  debug "debug log"
  info "information log"
  warn "warning log"
  error "error log"
  log -30 "custom log severity"
  fatal "fatal log, script will exit with code 1"
}

function help_message() {
  cat <<END

  $SCRIPT_DESCRIPTION

Usage:
  $SCRIPT_NAME [options] [command] [args]

Available Commands:
  help                    Display detailed help.
  version                 Print version information.

Options:
  --help, -h              Alias help command.
  --version, -v           Alias version command.
  --force                 Don't ask for confirmation.
  --log-level             Set the log level severity. Lower level will be
                          ignored. Must be an integer or a level name:
                          ${SEVERITY_RANGES_NAMES[@]}.
  --                      Denotes the end of the options.  Arguments after this
                          will be handled as parameters even if they start with
                          a '-'.
END
}

# -----------------------------------------------------------------------------
# Run the script
# -----------------------------------------------------------------------------
parse_and_execute "$@"
